version: '3.8'

services:
  php-fpm:
    build:
      context: ./etc/php
      dockerfile: Dockerfile
    container_name: mapos_app
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      # Variáveis injetadas pela Coolify
      - MYSQL_HOST=${MYSQL_MAPOS_HOST}
      - MYSQL_DATABASE=${MYSQL_MAPOS_DATABASE}
      - MYSQL_USER=${MYSQL_MAPOS_USER}
      - MYSQL_PASSWORD=${MYSQL_MAPOS_PASSWORD}

  # Serviço Web (Nginx)
  nginx:
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile  # Aponta para o novo Dockerfile que criamos
    container_name: mapos_nginx
    restart: always
    ports:
      - "${NGINX_PORT:-8000}:8000"
    volumes:
      - .:/var/www/html # Nginx ainda precisa ver os arquivos estáticos
      # AVISO: Removemos o volume do default.conf pois agora ele está dentro da imagem
    depends_on:
      - php-fpm