version: '3.8'

services:
  php-fpm:
    build:
      context: ./etc/php
      dockerfile: Dockerfile
    container_name: mapos_app
    restart: always
    volumes:
      - .:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./etc/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      # Variáveis injetadas pela Coolify
      - MYSQL_HOST=${MYSQL_MAPOS_HOST}
      - MYSQL_DATABASE=${MYSQL_MAPOS_DATABASE}
      - MYSQL_USER=${MYSQL_MAPOS_USER}
      - MYSQL_PASSWORD=${MYSQL_MAPOS_PASSWORD}

  # Serviço Web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: mapos_nginx
    restart: always
    ports:
      - "${NGINX_PORT:-8000}:8000"
    volumes:
      - .:/var/www/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm